CREATE DATABASE Session2_Th3_QuanLySinhVien;
USE Session2_Th3_QuanLySinhVien;
CREATE TABLE Class(
ClassID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ClassName VARCHAR(60) NOT NULL ,
StartDate DATETIME NOT NULL ,
Status BIT 
);
CREATE TABLE Student(
StudentId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
StudentName VARCHAR(30) NOT NULL,
Address VARCHAR(20) NOT NULL,
Status BIT,
ClassId INT NOT NULL,
FOREIGN KEY (ClassId) REFERENCES Class(ClassID) 
);

CREATE TABLE Subject(
SubId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
SubName VARCHAR(30) NOT NULL ,
Credit TINYINT NOT NULL DEFAULT(1) CHECK(Credit >=1),
Status BIT DEFAULT(1) 
);
CREATE TABLE Mark(
MarkID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
SubID INT NOT NULL UNIQUE KEY,
FOREIGN KEY(SubID) REFERENCES Subject(SubId),
StudentID INT NOT NULL UNIQUE KEY,
FOREIGN KEY(StudentID) REFERENCES Student(StudentId),
Mark FLOAT DEFAULT(0) CHECK(1 <= Mark <= 100),
ExamTime TINYINT DEFAULT(1)
);
