CREATE DATABASE Session2_Th2_QuanLyDiemthi;
USE Session2_Th2_QuanLyDiemthi;
monhocCREATE TABLE HocSinh(
MaHS VARCHAR(50) PRIMARY KEY,
NgaySinh DATETIME,
Lop VARCHAR(20),
GT VARCHAR(20)
);
CREATE TABLE MonHoc(
MaMH VARCHAR(20) PRIMARY KEY,
TenMH VARCHAR(20)
);
CREATE TABLE BangDiem(
MaHS VARCHAR(20),
MaMH VARCHAR(20),
DiemThi INT,
NgayKT DATETIME,
-- Set khóa chính khóa ngoại
PRIMARY KEY(MaHS, MaMH),
FOREIGN KEY(MaHS) REFERENCES HocSinh(MaHS),
FOREIGN KEY(MaMH) REFERENCES MonHoc(MaMH)
);
CREATE TABLE GiaoVien(
MaGV VARCHAR(30) PRIMARY KEY,
TenGV VARCHAR(30),
SDT VARCHAR(10)
);

ALTER TABLE MonHoc ADD MaGV VARCHAR(20);
ALTER TABLE MonHoc ADD CONSTRAINT Fk_MaGV FOREIGN KEY(MaGV) REFERENCES GiaoVien(MaGV);
